dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=legacy setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: ClM7WdrRoZdc3tW7JlaoqDCSSGfJSD7urp8iUQVuZgj0n4xPmNowVPEwF9u34ZutDbrHNb+UP+qedxaNAZoNRkG94w/+uZHxrWmZgtKOdhEwdIaeLwlMwrF02bwnHuStsfWuCbwcbLQ+QKvygIjNQ9b1nKLZng8cbmLn0JpQ5lo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
